name: Build Web API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Ecommerce.Orders.Api/Ecommerce.Orders.Api.csproj

      - name: Build
        run: dotnet build Ecommerce.Orders.Api/Ecommerce.Orders.Api.csproj --no-restore --configuration Release
